#! /bin/sh

#
# Copyright (c) 2024 Logan Ryan McLintock
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#


# Mirror:
# Mirrors the source directory to the destination directory.

set -e
set -u

if [ "$#" -ne 2 ]
then
    printf 'Usage: %s source_dir dest_dir\n' "$0" 1>&2
    exit 1
fi

source_dir="$1"
dest_dir="$2"

if [ ! -d "$source_dir" ]
then
    printf '%s: Error: source_dir does not exist: %s\n' "$0" "$source_dir" 1>&2
    exit 1
fi

if [ ! -d "$dest_dir" ]
then
    printf '%s: Error: dest_dir does not exist: %s\n' "$0" "$dest_dir" 1>&2
    exit 1
fi

rsync -aHv --delete --force "$source_dir"/ "$dest_dir"
